### ISSUE TITLE
Projects not found when opening DotNet Solution

### ISSUE THREAD

**Issue by markti** [Azure/azure-mobile-apps-quickstarts#14]
ZUMOAPPNAMEService is unavailable. Did somebody forget to check in a csproj file?

**Comment by phvannor** [comment]
The projects are not directly consumable, you'll notice that the file in question is checked in as a .tt file instead, with placeholders for the nupkg versions/etc to be populated in. In order to generate a usable version, you need to run msbuild.exe as noted in the readme or grab the appriate QS for the portal instead directly.
