### ISSUE TITLE
Update empty node site. Add api folder to both templates.

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-quickstarts#22]
Empty site requires updating to RC3.

When cloning from a git repo, the api folder doesn't get created, pretty sure this is because the folder doesn't get commited to git. Fix is to add a readme.md?

**Comment by danderson00** [comment]
Not having the api folder causes a few issues - the site doesn't start and the Easy APIs tile is broken.

**Comment by fabiocav** [comment]
The folder is not present because this template is used to generate the package used by the management service, which is a ZIP file, so empty folders are not supported. 
The deployment process executes the script that is added to the package when it is deployed. To test this, we should trigger one of the quickstart builds to generate a package, which will have the script that gets executed.
Yes, having a folder with a placeholder file in it (like a readme) would allow us to have the folder in the ZIP, but we'd either be leaving an unnecessary file behind, or we'd have to delete the file as part of the deployment.
If we decide to add the folder, we need to update the deployment script so it no longer tries to create them during the deployment. So we need to coordinate this work.
We can also (probably should) commit the script and the deployment folder with the template structure here.

**Comment by danderson00** [comment]
The placeholder needs to be left in so that the folder is created in github and created when the repo is cloned, particularly on monaco or when deploying to "productioin".

**Comment by danderson00** [comment]
I'm thinking in the scenario where a user does the quickstart and pushes to a github repo from monaco. Cloning that results in a broken mobile app.

**Comment by danderson00** [comment]
Or we could make it so that mobileApp.tables.import of a folder that doesn't exist doesn't crash the app. Might be a better approach.

**Comment by fabiocav** [comment]
I see. Yes, we can definitely have the placeholder to avoid that problem, but if we could change _import_ so it handles missing folder that would be nice. It would definitely be a more robust solution. I can see people deleting any placeholder file we end up putting there and getting into trouble.

**Comment by fabiocav** [comment]
Didn't mean to close the issue. Re-opened.
